export const BLOCK_BEGIN = '<!-- BEGIN agent-rules -->';
export const BLOCK_END = '<!-- END agent-rules -->';

const NOTICE = '<!-- Generated by agent-rules. Edits inside this block are overwritten. -->';

export const wrapBlock = (body) => [BLOCK_BEGIN, NOTICE, '', body.trim(), BLOCK_END].join('\n');

export const hasBlock = (text) => text.includes(BLOCK_BEGIN) && text.includes(BLOCK_END);

const replaceBlock = (text, block) => {
  const start = text.indexOf(BLOCK_BEGIN);
  const end = text.indexOf(BLOCK_END) + BLOCK_END.length;
  return text.slice(0, start) + block + text.slice(end);
};

const appendBlock = (text, block) => {
  const existing = text.replace(/\s*$/, '');
  if (existing === '') return `${block}\n`;
  return `${existing}\n\n${block}\n`;
};

export const upsertBlock = (text, block) => {
  if (hasBlock(text)) return replaceBlock(text, block);
  return appendBlock(text, block);
};

export const removeBlock = (text) => {
  if (!hasBlock(text)) return text;
  const start = text.indexOf(BLOCK_BEGIN);
  const end = text.indexOf(BLOCK_END) + BLOCK_END.length;
  return (text.slice(0, start).replace(/\s*$/, '') + '\n' + text.slice(end).replace(/^\s*/, '')).replace(/^\n/, '');
};
